### PR TITLE
Remove initial state for amount in AddTransaction.tsx so that placeho…

### LINKED ISSUE #166: When adding a transaction, the user should not have to manually clear the "Amount" field
Under "Add New Transaction", The "Amount" field contains a `0` that is not cleared when selecting the field.

The best way is probably to just remove the value that is there by default, and use placeholders like for the other fields.

### PR DESCRIPTION
**Pull request by KaizerTilt**
Fixes #166

### CODE REVIEW

**Comment by FredrikAugust** [comment]
Don't have the ability to try this out, but doesn't this potentially throw an error during submitting, as you're trying to multiply a possibly undefined value with 100. If so, you could add an `|| 0` after `amount` in the `handleSubmit` function.

**Comment by FredrikAugust** [comment]
The reason for this is that the type of the function called in the callback has amount defined as a number, whereas it is `number | undefined` here.

**Comment by KaizerTilt** [comment]
Good catch @FredrikAugust , it threw an error to the console that I didn't catch at first. I'll push and merge the change for the time being, but I wonder if this is something we should revisit when we implement form validation in the future. I'm thinking that this field should be required when creating a transaction, and for me at least it would not make sense to create a transaction with amount = 0. What's your thoughts on this?

**Comment by KaizerTilt** [comment]
@FredrikAugust 
Another issue arises when not giving an initial integer value to the amount state, as react complains that the input component switches from being an uncontrolled to a controlled component:
```Warning: A component is changing an uncontrolled input of type number to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component.```

To me it seems like the value is managed by the input element itself while the amount-state is undefined, but switches to a controlled component (value controlled by react) once input is given and the setAmount function is called. Don't immediately see a way around this while still keeping the initial state undefined. Thoughts?

**Pull request merged**
